development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: Daddys40_development
  pool:     5
  username: Daddys40
  password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: Daddys40_test
  pool:     5
  username: Daddys40
  password:
  template: template0


production:
  adapter:  postgresql
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
